steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/multiagentes-ia/agentic-rag-service:latest', '.']
    timeout: '1200s'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/multiagentes-ia/agentic-rag-service:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agentic-rag-service'
      - '--image'
      - 'gcr.io/multiagentes-ia/agentic-rag-service:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,USE_EMBEDDED_CHROMA=true,PYTHONUNBUFFERED=1'

images:
  - 'gcr.io/multiagentes-ia/agentic-rag-service:latest'

options:
  machineType: 'E2_HIGHCPU_8'